# escape=`
FROM plugins/base:windows-1809

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone PyPi" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

# TODO: install required tools

ADD release/windows/amd64/drone-pypi.exe C:/bin/drone-pypi.exe
ENTRYPOINT [ "C:\\bin\\drone-pypi.exe" ]
