FROM plugins/base:linux-arm

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone PyPi" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add -U ca-certificates python3 && \
    rm -rf /var/cache/apk/* && \
    pip3 install --no-cache-dir --upgrade pip setuptools wheel six twine

ADD release/linux/arm/drone-pypi /bin/
ENTRYPOINT ["/bin/drone-pypi"]
